export const ADD_TO_CART = "ADD_TO_CART";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
export const REMOVE_ITEM = "REMOVE_ITEM";
