# Generated by Django 4.0.dev20210525112240 on 2021-08-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0002_alter_product_price_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='products',
        ),
    ]
